import { DreamHeader, DreamSubnav } from "./features/dream/DreamOverviewPage";
import { DreamPolicyWizard } from "./features/dream/DreamPolicyWizard";
import { backfillDreamPolicy, checkDreamPolicy, decideDreamPolicy, disableDreamPolicy, publishDreamPolicy, submitDreamPolicyReview, type BasicDreamPolicy, type DreamPolicyLifecycle } from "./api/dream";
import { useState } from "react";
import "./features/dream/dream.css";

export function DreamPolicyPanel({ organizations = [], advancedAllowed = false, advancedMode = false, currentUserID = "", onSubmit }: { organizations?: Array<{ id: string; name: string }>; advancedAllowed?: boolean; advancedMode?: boolean; currentUserID?: string; onSubmit?: (value: BasicDreamPolicy) => DreamPolicyLifecycle | void | Promise<DreamPolicyLifecycle | void> }) {
  const [policy, setPolicy] = useState<DreamPolicyLifecycle | null>(null); const [error, setError] = useState("");
  const run = async (task: () => Promise<DreamPolicyLifecycle | void>) => { setError(""); try { const value = await task(); if (value) setPolicy(value); } catch (reason) { setError(reason instanceof Error ? reason.message : "操作没有完成"); } };
  return <main className="dream-page"><DreamHeader title="梦境工作流" description="用简单选择告诉系统整理哪个组织、使用哪些记录，以及什么时候需要负责人确认。" /><DreamSubnav current="workflow" /><p className="dream-state"><strong>这里的设置只影响之后的新运行</strong><span>历史梦境结果和已发布工作流不会被改写。</span></p><DreamPolicyWizard organizations={organizations} advancedAllowed={advancedAllowed} advancedMode={advancedMode} onSubmit={(value) => run(async () => await onSubmit?.(value))} />{policy ? <DreamPolicyLifecycleControls policy={policy} currentUserID={currentUserID} advancedMode={advancedMode} onSubmitReview={() => run(async () => { await checkDreamPolicy(policy.dream_policy_id, policy.revision); return submitDreamPolicyReview(policy.dream_policy_id, policy.revision, "publish"); })} onDecide={(decision) => run(() => decideDreamPolicy(policy.dream_policy_id, policy.revision, decision))} onPublish={() => run(() => publishDreamPolicy(policy.dream_policy_id, policy.revision))} onDisable={() => run(async () => submitDreamPolicyReview(policy.dream_policy_id, policy.revision, "disable"))} onFinalizeDisable={() => run(() => disableDreamPolicy(policy.dream_policy_id, policy.revision))} onBackfill={(start, end) => run(async () => { await backfillDreamPolicy(policy.dream_policy_id, start, end); })} /> : null}{error ? <p className="dream-state" role="alert"><strong>操作没有完成</strong><span>{error}</span><span>下一步：检查当前状态和权限后重试。</span></p> : null}</main>;
}

export function DreamPolicyLifecycleControls({ policy, currentUserID, advancedMode = false, onSubmitReview, onDecide, onPublish, onDisable, onFinalizeDisable, onBackfill }: { policy: DreamPolicyLifecycle; currentUserID: string; advancedMode?: boolean; onSubmitReview: () => void; onDecide: (decision: "approve" | "reject") => void; onPublish: () => void; onDisable?: () => void; onFinalizeDisable?: () => void; onBackfill?: (start: string, end: string) => void }) {
  const isReviewer = policy.review_mode === "upward_review" && policy.reviewer_user_id === currentUserID && policy.requester_user_id !== currentUserID;
  const [backfillStart, setBackfillStart] = useState(""); const [backfillEnd, setBackfillEnd] = useState("");
  return <section className="dream-advanced" aria-label="梦境工作流发布状态"><h2>检查与发布</h2>{policy.status === "draft" ? <><p>草稿已保存，尚未影响后续运行。系统会先检查风险，再按组织架构安排确认。</p><div className="dream-actions"><button className="dream-primary" onClick={onSubmitReview}>检查并提交复核</button></div></> : null}{policy.status === "review_pending" ? <>{policy.review_mode === "upward_review" ? <p>已提交给上级负责人复核</p> : policy.review_mode === "enterprise_knowledge_admin_queue" ? <p>已进入企业知识管理员待分配队列</p> : <p>等待发起人确认这项低风险变更</p>}{isReviewer || policy.review_mode === "single_confirmation" && policy.requester_user_id === currentUserID ? <div className="dream-actions"><button className="dream-secondary" onClick={() => onDecide("reject")}>驳回</button><button className="dream-primary" onClick={() => onDecide("approve")}>批准发布</button></div> : null}</> : null}{policy.status === "approved" && policy.pending_action === "publish" ? <><p>复核已通过。最后发布后才会影响新的梦境运行。</p><div className="dream-actions"><button className="dream-primary" onClick={onPublish}>发布新版本</button></div></> : null}{policy.status === "published" ? <><p>已发布第 {policy.version} 版，后续运行会使用这个固定版本。</p>{advancedMode ? <><div className="dream-wizard-grid"><label className="dream-field">补跑开始时间<input aria-label="补跑开始时间" type="datetime-local" value={backfillStart} onChange={(event) => setBackfillStart(event.target.value)} /></label><label className="dream-field">补跑结束时间<input aria-label="补跑结束时间" type="datetime-local" value={backfillEnd} onChange={(event) => setBackfillEnd(event.target.value)} /></label></div><div className="dream-actions">{onDisable ? <button className="dream-secondary" onClick={onDisable}>申请停用</button> : null}{onBackfill ? <button className="dream-secondary" disabled={!backfillStart || !backfillEnd} onClick={() => onBackfill(new Date(backfillStart).toISOString(), new Date(backfillEnd).toISOString())}>补跑所选时间段</button> : null}</div></> : null}</> : null}{policy.status === "approved" && policy.pending_action === "disable" ? <><p>停用复核已通过。完成停用后不会再创建新的自动运行。</p>{onFinalizeDisable ? <div className="dream-actions"><button className="dream-primary" onClick={onFinalizeDisable}>完成停用</button></div> : null}</> : null}{policy.status === "disabled" ? <p>这条工作流已停用，不会再创建新的自动运行。</p> : null}</section>;
}
