import { useState } from "react";
import { AlertCircle, CheckCircle2, FileSearch, History, LockKeyhole, RotateCcw } from "lucide-react";
import type { DreamAnnotation, DreamRun } from "../../api/dream";
import { operationKey } from "../../api/dream";
import { DreamHeader } from "./DreamOverviewPage";
import "./dream.css";

export function DreamRunDetailPage({ run, organizationName = run.organization_name ?? "授权组织", onAnnotate, onRerun, onEvidenceAccess }: { run: DreamRun; organizationName?: string; onAnnotate?: (action: DreamAnnotation["action"], comment: string) => Promise<unknown>; onRerun?: (key: string) => Promise<{ handle: string }>; onEvidenceAccess?: () => Promise<{ sanitized_detail: string }> }) {
  const [message, setMessage] = useState("");
  const [evidence, setEvidence] = useState("");
  const [comment, setComment] = useState("");
  const annotate = async (action: DreamAnnotation["action"], text = "") => { await onAnnotate?.(action, text); setMessage("批注已追加，历史结果没有被修改。"); };
  const requestEvidence = async () => { setEvidence(""); try { const value = await onEvidenceAccess?.(); setEvidence(value?.sanitized_detail ?? "没有可显示的已脱敏内容。"); } catch (error) { setEvidence((error as { status?: number }).status === 403 ? "当前没有查看权限。请联系该组织的负责人授权后再试。" : "暂时无法申请查看依据，请稍后重试。"); } };
  return <main className="dream-page">
    <DreamHeader title="运行与追溯" description={`${organizationName}在这个时间段的不可变整理结果、输入覆盖和处理记录。`} />
    <div className="dream-immutable"><LockKeyhole size={17} /><strong>这是历史运行结果，不能直接修改</strong><span>如有问题，请追加批注或重新整理。</span></div>
    <div className="dream-run-grid"><section className="glass-rest"><h2>整理结果</h2><p className="dream-summary">{run.display_summary || "本次运行没有生成可用摘要。"}</p><Meta run={run} /><SignalList title="事实与主题" items={[...run.facts, ...run.themes]} /><SignalList title="趋势" items={run.trends} /><SignalList title="风险" items={run.risks} /><SignalList title="待办" items={run.todos} />{run.failure_stage ? <p className="dream-evidence-result"><AlertCircle size={16} /> 失败阶段：{run.failure_stage}</p> : null}</section>
      <aside className="glass-rest"><h2>输入与血缘</h2><ul className="dream-detail-list"><li>下级组织输入 <strong>{run.coverage.completed_children}/{run.coverage.expected_children}</strong><small>{run.missing_input_reasons.length ? `${run.missing_input_reasons.length} 项没有完成` : "输入完整"}</small></li>{run.missing_input_reasons.map((reason, index) => <li key={`missing-${index}`}><AlertCircle size={15} /><small>{reason}</small></li>)}{(run.input_organizations ?? []).map((item, index) => <li key={`${item.handle}-${index}`}><strong>{item.organization_name}</strong><small>{item.relation}</small></li>)}{(run.downstream_organizations ?? []).map((item, index) => <li key={`downstream-${item.handle}-${index}`}><strong>{item.organization_name}</strong><small>{item.relation}</small></li>)}{run.rerun ? <li><History size={15} /> {run.rerun_relation || "这是一次重新整理的结果"}</li> : null}</ul>
        <h2>历史处理记录</h2>{run.annotations?.length ? <ul className="dream-detail-list">{run.annotations.map((item, index) => <li key={`${item.created_at}-${index}`}><strong>{item.actor_name || "维护人员"}</strong><small>{item.comment || annotationLabel(item.action)}</small></li>)}</ul> : <p className="dream-meta-label">还没有批注</p>}
        <h2>追加处理记录</h2><div className="dream-annotation-actions"><button className="dream-secondary" onClick={() => void annotate("confirm")}><CheckCircle2 size={15} />确认结果</button><button className="dream-secondary" onClick={() => void annotate("reject")}>驳回结果</button><button className="dream-secondary" onClick={() => void annotate("mark_incorrect")}>标记结果有误</button></div><label className="dream-field">补充说明<textarea value={comment} onChange={(event) => setComment(event.target.value)} maxLength={4000} /></label><button className="dream-secondary" onClick={() => void annotate("comment", comment)} disabled={!comment.trim()}>添加批注</button>{message ? <p role="status">{message}</p> : null}
        <h2>重新整理与依据</h2><div className="dream-annotation-actions"><button className="dream-primary" onClick={() => void onRerun?.(operationKey("rerun", run.handle, `${run.window_start}:${run.window_end}`))}><RotateCcw size={15} />重新整理这个时间段</button><button className="dream-secondary" onClick={() => void requestEvidence()}><FileSearch size={15} />申请查看原始依据</button></div>{evidence ? <div className="dream-evidence-result" role="status">{evidence}</div> : null}</aside></div>
  </main>;
}
function annotationLabel(action: DreamAnnotation["action"]) { return action === "confirm" ? "确认结果" : action === "reject" ? "驳回结果" : action === "mark_incorrect" ? "标记结果有误" : "补充说明"; }
function SignalList({ title, items }: { title: string; items: DreamRun["facts"] }) { return <section><h2>{title}</h2>{items.length ? <ul className="dream-detail-list">{items.map((item, index) => <li key={`${item.title}-${index}`}><strong>{item.title}</strong><small>{item.detail}</small></li>)}</ul> : <p className="dream-meta-label">本次没有{title}</p>}</section>; }
function Meta({ run }: { run: DreamRun }) { return <div className="dream-toolbar"><span>{new Date(run.window_start).toLocaleString("zh-CN")} 至 {new Date(run.window_end).toLocaleString("zh-CN")}</span><span className="dream-status" data-state={run.status === "failed" ? "attention" : "ok"}>{run.status === "succeeded" ? "已完成" : run.status === "waiting_confirmation" ? "等待确认" : run.status === "failed" ? "失败" : "处理中"}</span></div>; }
